apiVersion: v1
kind: Service
metadata:
  name: {{ include "ntpd-rs.fullname" . }}-metrics
  labels: {{- include "ntpd-rs.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 9975
      protocol: TCP
      name: metrics
  selector: {{- include "ntpd-rs.selectorLabels" . | nindent 4 }}
