name: ci
on:
  push:
    tags:
    - '*'
jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Read env
      run: cat .env >> ${GITHUB_ENV}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        build-args: |
          NTPD_RS_VERSION=${{ env.NTPD_RS_VERSION }}
        tags: ghcr.io/whitestack/ntpd-rs:${{ github.ref_name }}
